
version: "3"

services:
    helloworld-prod-go-app:
        depends_on:
            - helloworld-prod-go-go
        image: nginx:1.27.2
        volumes:
            - ./app:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8080:80
        tty: true
        working_dir: /var/www/html
    helloworld-prod-go-go:
        build:
            context: .
            dockerfile: ./go/Dockerfile
        volumes:
            - ./app:/var/www/html
        working_dir: /var/www/html
